start homework
Maksimpv1/FE46-Popov pull request #3
Opened 2023-02-03 19:51 UTC by Maksimpv1

2023-02-07 17:10 UTC, UladTeachMeSkills requested changes

2023-02-07 17:10 UTC, UladTeachMeSkills commented on Lesson-5/contact/index.html
> +                            <input type="text" >
Убрать label
Добавить placeholder

2023-02-07 17:10 UTC, UladTeachMeSkills commented on Lesson-5/reviews/index.html
> +                    <div></div>
same

2023-02-07 17:10 UTC, UladTeachMeSkills commented on Lesson-5/reviews/index.html
> +                            <div class="mes-card__triangle"><img src="./img/triangle.png"></div>
Используй псевдоэлемент :)

2023-02-07 21:42 UTC, Maksimpv1 commented on Lesson-5/banner_2/index.html
> +    <section class="banner-2">
Ничего если я в комментах для себя буду отмечать что сделал?
тут вроде поправил все

2023-02-07 21:53 UTC, Maksimpv1 commented on Lesson-5/banner_2/index.html
> +                            <div></div>
Тут я линии со всех секций сделал с одним классом

2023-02-07 21:58 UTC, Maksimpv1 commented on Lesson-5/banner_2/index.html
> +                            <button>Download</button>
Поправил

2023-02-07 22:05 UTC, Maksimpv1 commented on Lesson-5/banner_2/style.css
> +    margin-right: auto;
Во всех css поправил

2023-02-07 22:07 UTC, Maksimpv1 commented on Lesson-5/contact/index.html
> +                </div>
Поправил

2023-02-07 22:07 UTC, Maksimpv1 commented on Lesson-5/contact/index.html
> +                    <input type="submit" value="Send Message">
Поправил

2023-02-07 22:13 UTC, Maksimpv1 commented on Lesson-5/contact/index.html
> +                            <input type="text" >
Убрал label
Добавил placeholder

2023-02-07 22:13 UTC, Maksimpv1 commented on Lesson-5/reviews/index.html
> +                            <div class="mes-card__triangle"><img src="./img/triangle.png"></div>
Уф постараюсь )

2023-02-08 15:39 UTC, UladTeachMeSkills approved these changes

2023-02-08 15:39 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-banner.css
> +  margin: 0 auto;;
Лишняя точка с запятой

2023-02-08 15:45 UTC, merged