burger menu
Maksimpv1/FE46-Popov pull request #7
Opened 2023-02-17 19:38 UTC by Maksimpv1

2023-02-19 15:42 UTC, UladTeachMeSkills requested changes

2023-02-19 15:42 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-about.css
>      font-family: "Raleway", sans-serif;
Пересмотри пожалуйста все свои шрифты. У тебя в body должен быть установлен один общий шрифт и убраны его дубликаты во всех остальных стилях

2023-02-19 15:42 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-header.css
> +}
А зачем такая макаронная фабрика? :)

2023-02-19 15:42 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-header.css
> +@media screen and (max-width:1300px){
Немного странно что у тебя разваливается хедер при такой ширине экрана

2023-02-19 15:42 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-tabs.css
> +  height: 460px;
Ууууу

2023-02-20 23:16 UTC, Maksimpv1 commented
добавил домашку 1 и 2 задание

2023-02-20 23:18 UTC, Maksimpv1 commented on axit-project/allstyles/style-header.css
> +@media screen and (max-width:1300px){
Это небольшая анимация для лого

2023-02-20 23:18 UTC, Maksimpv1 commented on axit-project/allstyles/style-header.css
> +}
Это пока в разработке (

2023-02-21 08:04 UTC, UladTeachMeSkills requested changes

2023-02-21 08:04 UTC, UladTeachMeSkills commented on Lesson-8/Form_one/style.css
> +    font-family: 'Montserrat';
Можно добавить в тег body и в дальнейшем не дублировать

2023-02-21 08:04 UTC, UladTeachMeSkills commented on Lesson-8/Form_two/style.css
> +    font-family: 'Montserrat';
same

2023-02-21 08:04 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        <li><a class="sidebar-text" href="#">Contact</a></li>
Сделай ссылки на id соответствующих секций

2023-02-21 08:04 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        </div> -->
Убери ненужное

2023-02-21 08:04 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        </div> -->
same

2023-02-22 06:42 UTC, Maksimpv1 commented on axit-project/allstyles/style-tabs.css
> +  height: 460px;
Там js в index.html для секции табов и из за него нужна фиксированная ширина(  иначе нижний блок налезает на табы)

2023-02-22 06:42 UTC, Maksimpv1 commented on axit-project/index.html
> +                        <li><a class="sidebar-text" href="#">Contact</a></li>
Сделал

2023-02-22 06:42 UTC, Maksimpv1 commented on axit-project/index.html
> +                        </div> -->
Убрал

2023-02-22 06:42 UTC, Maksimpv1 commented on axit-project/index.html
> +                        </div> -->
убрал

2023-02-22 13:21 UTC, UladTeachMeSkills requested changes

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-about.css
>      font-family: "Raleway", sans-serif;
Не пофикшено

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-about.css
> +    font-family: "Raleway", sans-serif;
same

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-about.css
> +    font-family: "One sans", sans-serif;
same

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/allstyles/style-tabs.css
> +  height: 540px;
:(

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                                <li><a class="menu-text" href="#features_ya">Features</a></li>
Что за приписка ya?)

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/index.html
>      const tabOne = document.getElementById("tab-one");
Вынеси в отдельный файл JS

2023-02-22 13:21 UTC, UladTeachMeSkills commented on axit-project/index.html
>      const tabOne = document.getElementById("tab-one");
Имею ввиду весь тег скрипт

2023-02-23 07:28 UTC, Maksimpv1 commented on axit-project/allstyles/style-tabs.css
> +  height: 540px;
Там сложная схема с табами, если убрать фиксированную ширину то блок about наплывает поверх табов(почему я пока не понял, но походу в этом замешан js)

2023-02-23 12:26 UTC, Maksimpv1 commented on axit-project/index.html
> +                                <li><a class="menu-text" href="#features_ya">Features</a></li>
ya - я (якорь) По айди

2023-02-23 14:04 UTC, Maksimpv1 commented on axit-project/allstyles/style-about.css
>      font-family: "Raleway", sans-serif;
пофиксил

2023-02-23 14:06 UTC, Maksimpv1 commented on Lesson-8/Form_one/style.css
> +    font-family: 'Montserrat';
Добавил

2023-02-23 14:08 UTC, Maksimpv1 commented on Lesson-8/Form_two/style.css
> +    font-family: 'Montserrat';
Добавил

2023-02-23 14:08 UTC, Maksimpv1 commented on axit-project/allstyles/style-about.css
> +    font-family: "Raleway", sans-serif;
убрал

2023-02-23 14:08 UTC, Maksimpv1 commented on axit-project/allstyles/style-about.css
>      font-family: "Raleway", sans-serif;
пофиксил

2023-02-23 14:09 UTC, Maksimpv1 commented on axit-project/allstyles/style-about.css
> +    font-family: "One sans", sans-serif;
Это как не основной шрифт

2023-02-25 12:26 UTC, UladTeachMeSkills approved these changes

2023-02-27 06:07 UTC, merged