video player v0.1
Maksimpv1/FE46-Popov pull request #8
Opened 2023-02-23 00:15 UTC by Maksimpv1

2023-02-23 09:11 UTC, UladTeachMeSkills requested changes

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.html
> +                        <source src="./last_off_us.mp4">
the last of us!

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.html
> +                    <progress class="progress-bar" id="progresshtml" max="100" value="10"></progress>
input type range

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.html
> +                    </div>            -->
Delete

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.js
> +const volumeV = document.getElementById('volume');
Почему в первом случае let а во втором const?

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.js
> +document.querySelector('#volume').oninput = videoVolume;
Определи для начала переменные и используй коллбэки из стрелочных/деклорированых функций на них

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.js
> +    }
Используй условный оператор "?"

2023-02-23 09:11 UTC, UladTeachMeSkills commented on Lesson-add/index.js
> +    let sec = this.value;
На кого ссылается this?

2023-02-23 11:08 UTC, Maksimpv1 commented on Lesson-add/index.html
> +                        <source src="./last_off_us.mp4">
ой )

2023-02-23 11:09 UTC, Maksimpv1 commented on Lesson-add/index.html
> +                    </div>            -->
я хочу это добавить, только думаю как ( наверно раскрывающимся списком лучше будет, типо как настройки)

2023-02-23 14:27 UTC, Maksimpv1 commented on Lesson-add/index.html
> +                        <source src="./last_off_us.mp4">
пофиксил

2023-02-23 14:28 UTC, Maksimpv1 commented on Lesson-add/index.html
> +                    <progress class="progress-bar" id="progresshtml" max="100" value="10"></progress>
Сделал

2023-02-23 14:29 UTC, Maksimpv1 commented on Lesson-add/index.js
> +const volumeV = document.getElementById('volume');
пофиксил

2023-02-25 12:23 UTC, UladTeachMeSkills approved these changes

2023-02-28 09:28 UTC, UladTeachMeSkills approved these changes

2023-02-28 16:51 UTC, merged